#!/usr/bin/env python3
"""Generate gpu_tables.inc from offsets.yaml.

Produces a Rust include file with the GPU_TABLES constant, consumed via
include!() by gddr7_temp.rs (kbuild compiles exactly one .rs per module
object, so the table cannot live in a second source file)."""
import sys
import yaml

VRAM_TYPES = {"VRAM_GDDR7_DQR", "VRAM_GDDR6_ADC", "VRAM_NONE"}
THERM_TYPES = {"THERM_BLACKWELL_BJT", "THERM_LEGACY_BYTE", "THERM_NONE"}

# Rust enum variant names for each YAML type string.
VRAM_TYPE_RUST = {
    "VRAM_GDDR7_DQR": "VramType::Gddr7Dqr",
    "VRAM_GDDR6_ADC": "VramType::Gddr6Adc",
    "VRAM_NONE": "VramType::Absent",
}
THERM_TYPE_RUST = {
    "THERM_BLACKWELL_BJT": "ThermType::BlackwellBjt",
    "THERM_LEGACY_BYTE": "ThermType::LegacyByte",
    "THERM_NONE": "ThermType::Absent",
}


def format_hex(v):
    """Render a YAML integer (or 0x-prefixed string) as a Rust hex literal."""
    if isinstance(v, str) and v.startswith("0x"):
        return v
    return hex(int(v))


def escape_rust_string(s: str) -> str:
    """Escape backslashes and double quotes for Rust string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _resolve_vram_type(type_str, name):
    """Resolve VRAM type from YAML. Defaults to VRAM_NONE if block is absent."""
    t = type_str if isinstance(type_str, str) else "VRAM_NONE"
    if t not in VRAM_TYPES:
        sys.exit(f"gen_offsets: unknown vram_type '{t}' in {name}")
    return t


def _resolve_therm_type(type_str, name):
    """Resolve THERM type from YAML. Defaults to THERM_NONE if block is absent."""
    t = type_str if isinstance(type_str, str) else "THERM_NONE"
    if t not in THERM_TYPES:
        sys.exit(f"gen_offsets: unknown therm_type '{t}' in {name}")
    return t


def _parse_device_id(t):
    return int(t["device_id"], 16) if isinstance(t["device_id"], str) else t["device_id"]


def _generate_entries(tables):
    """Generate Rust GpuOffsetTable entries from YAML tables."""
    seen_ids = set()
    for t in tables:
        dev_id = _parse_device_id(t)
        if dev_id in seen_ids:
            sys.exit(f"gen_offsets: duplicate device_id 0x{dev_id:04x}")
        seen_ids.add(dev_id)

        vram = t.get("vram", {})
        therm = t.get("therm", {})

        vram_type_str = _resolve_vram_type(vram.get("type"), t["name"])
        therm_type_str = _resolve_therm_type(therm.get("type"), t["name"])

        yield (
            f'    GpuOffsetTable {{ device_id: 0x{dev_id:04x}, name: "{escape_rust_string(t["name"])}",\n'
            f'      vram_type: {VRAM_TYPE_RUST[vram_type_str]},\n'
            f'      vram_module0: {format_hex(vram.get("module0", 0))}, '
            f'vram_vld_off: {format_hex(vram.get("vld_off", 0))},\n'
            f'      vram_stride: {format_hex(vram.get("stride", 0))}, '
            f'vram_num_modules: {vram.get("num_modules", 0)},\n'
            f'      therm_type: {THERM_TYPE_RUST[therm_type_str]},\n'
            f'      therm_ch0: {format_hex(therm.get("ch0", 0))}, '
            f'therm_ch_stride: {format_hex(therm.get("stride", 0))},\n'
            f'      therm_num_channels: {therm.get("num_channels", 0)} }},'
        )


def _write(tables, out_path):
    """Write the Rust include file (consumed via include!() by gddr7_temp.rs)."""
    entries_text = "\n".join(_generate_entries(tables))

    header = """\
// gpu_tables.inc — auto-generated by gen_offsets.py from offsets.yaml. DO NOT EDIT.

/// NVIDIA PCI vendor ID.
pub const NV_VENDOR_ID: u16 = 0x10de;

/// VRAM temperature readout scheme.
#[derive(Clone, Copy)]
pub enum VramType {
    /// GDDR7 data-quality-register temperature MR-code (Blackwell).
    Gddr7Dqr,
    /// GDDR6 12-bit ADC fixed-point value.
    Gddr6Adc,
    /// No VRAM temperature block on this GPU.
    Absent,
}

/// THERM register decode scheme.
#[derive(Clone, Copy)]
pub enum ThermType {
    /// Blackwell BJT: bit30 valid, lower 16 bits fixed-point 1/256 °C.
    BlackwellBjt,
    /// Legacy byte in bits 15:8; >= 127 is the invalid sentinel.
    LegacyByte,
    /// No THERM block on this GPU.
    Absent,
}

/// Per-GPU BAR0 offset table; num_modules/num_channels of 0 means the block
/// is absent on that GPU.
#[derive(Clone, Copy)]
pub struct GpuOffsetTable {
    /// PCI device ID this entry applies to.
    pub device_id: u16,
    /// Human-readable chip name (for log messages).
    pub name: &'static str,
    /// VRAM decode algorithm selector.
    pub vram_type: VramType,
    /// Base offset of module 0 data register within BAR0.
    pub vram_module0: u32,
    /// Offset from a module base to its validity register.
    pub vram_vld_off: u32,
    /// Byte stride between consecutive VRAM modules.
    pub vram_stride: u32,
    /// Number of VRAM modules (0 = block absent).
    pub vram_num_modules: i32,
    /// THERM decode algorithm selector.
    pub therm_type: ThermType,
    /// Base offset of channel 0 register within BAR0.
    pub therm_ch0: u32,
    /// Byte stride between consecutive THERM channels.
    pub therm_ch_stride: u32,
    /// Number of THERM channels (0 = block absent).
    pub therm_num_channels: i32,
}

/// Offset tables for all supported GPUs.
pub const GPU_TABLES: &[GpuOffsetTable] = &[
"""
    footer = "];\n"

    with open(out_path, "w") as f:
        f.write(header + entries_text + "\n" + footer)


def main(yaml_path, out_path):
    with open(yaml_path) as f:
        tables = yaml.safe_load(f)

    _write(tables, out_path)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
