#!/usr/bin/env python3
"""Generate gpu_offsets_generated.h from offsets.yaml.

Run at build time; output is committed nowhere as source of truth —
offsets.yaml is the source of truth, this file is derived."""
import sys
import yaml


def to_c_hex(v):
    if isinstance(v, str) and v.startswith("0x"):
        return v
    return hex(int(v))


def main(yaml_path, out_path):
    with open(yaml_path) as f:
        tables = yaml.safe_load(f)

    lines = [
        "/* AUTO-GENERATED from offsets.yaml by gen_offsets.py",
        " * Do not edit this file directly — edit offsets.yaml and rebuild. */",
        "",
        "#include \"gpu_offsets.h\"",
        "",
        "static const struct gpu_offset_table gpu_tables[] = {",
    ]
    seen_ids = set()
    for t in tables:
        dev_id = int(t["device_id"], 16) if isinstance(t["device_id"], str) else t["device_id"]
        if dev_id in seen_ids:
            sys.exit(f"gen_offsets: duplicate device_id 0x{dev_id:04x}")
        seen_ids.add(dev_id)

        lines.append(
            f'    {{ .device_id = 0x{dev_id:04x}, .name = "{t["name"]}",\n'
            f'      .dqr_module0 = {to_c_hex(t["dqr"]["module0"])}, '
            f'.dqr_vld_off = {to_c_hex(t["dqr"]["vld_off"])},\n'
            f'      .dqr_stride = {to_c_hex(t["dqr"]["stride"])}, '
            f'.dqr_num_modules = {t["dqr"]["num_modules"]},\n'
            f'      .therm_ch0 = {to_c_hex(t["therm"]["ch0"])}, '
            f'.therm_ch_stride = {to_c_hex(t["therm"]["stride"])},\n'
            f'      .therm_num_channels = {t["therm"]["num_channels"]} }},'
        )
    lines.append("};")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
