#!/usr/bin/env python3
"""Generate gpu_offsets_generated.h from offsets.yaml.

Produces a standalone header with the gpu_tables[] array definition.
The skeleton (struct + extern declarations) lives in gpu_offsets.h."""
import sys
import yaml

VRAM_TYPES = {"VRAM_GDDR7_DQR", "VRAM_GDDR6_ADC", "VRAM_NONE"}
THERM_TYPES = {"THERM_BLACKWELL_BJT", "THERM_LEGACY_BYTE", "THERM_NONE"}


def to_c_hex(v):
    if isinstance(v, str) and v.startswith("0x"):
        return v
    return hex(int(v))


def escape_c_string(s: str) -> str:
    """Escape backslashes and double quotes for C string literals."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _resolve_vram_type(type_str, name):
    """Resolve VRAM type from YAML. Defaults to VRAM_NONE if block is absent."""
    t = type_str if isinstance(type_str, str) else "VRAM_NONE"
    if t not in VRAM_TYPES:
        sys.exit(f"gen_offsets: unknown vram_type '{t}' in {name}")
    return t


def _resolve_therm_type(type_str, name):
    """Resolve THERM type from YAML. Defaults to THERM_NONE if block is absent."""
    t = type_str if isinstance(type_str, str) else "THERM_NONE"
    if t not in THERM_TYPES:
        sys.exit(f"gen_offsets: unknown therm_type '{t}' in {name}")
    return t


def _generate_entries(tables):
    """Generate C array initializer entries from YAML tables.

    Each entry may have 'vram', 'therm', or both blocks. Missing blocks
    default to all-zero fields (num_modules/num_channels == 0 means absent)."""
    seen_ids = set()
    for t in tables:
        dev_id = int(t["device_id"], 16) if isinstance(t["device_id"], str) else t["device_id"]
        if dev_id in seen_ids:
            sys.exit(f"gen_offsets: duplicate device_id 0x{dev_id:04x}")
        seen_ids.add(dev_id)

        vram = t.get("vram", {})
        therm = t.get("therm", {})

        vram_type_str = _resolve_vram_type(vram.get("type"), t["name"])
        therm_type_str = _resolve_therm_type(therm.get("type"), t["name"])

        yield (
            f'    {{ .device_id = 0x{dev_id:04x}, .name = "{escape_c_string(t["name"])}",\n'
            f'      .vram_type = {vram_type_str},\n'
            f'      .vram_module0 = {to_c_hex(vram.get("module0", 0))}, '
            f'.vram_vld_off = {to_c_hex(vram.get("vld_off", 0))},\n'
            f'      .vram_stride = {to_c_hex(vram.get("stride", 0))}, '
            f'.vram_num_modules = {vram.get("num_modules", 0)},\n'
            f'      .therm_type = {therm_type_str},\n'
            f'      .therm_ch0 = {to_c_hex(therm.get("ch0", 0))}, '
            f'.therm_ch_stride = {to_c_hex(therm.get("stride", 0))},\n'
            f'      .therm_num_channels = {therm.get("num_channels", 0)} }},'
        )


def main(yaml_path, out_path):
    with open(yaml_path) as f:
        tables = yaml.safe_load(f)

    entries_text = "\n".join(_generate_entries(tables))

    header = """\
/* gpu_offsets_generated.h — auto-generated by gen_offsets.py. DO NOT EDIT. */

#ifndef GPU_OFFSETS_GENERATED_H
#define GPU_OFFSETS_GENERATED_H

#include "gpu_offsets.h"

const struct gpu_offset_table gpu_tables[] = {
"""
    footer = f"""\
}};

const int gpu_tables_count = {len(tables)};

#endif /* GPU_OFFSETS_GENERATED_H */
"""

    with open(out_path, "w") as f:
        f.write(header + entries_text + "\n" + footer)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
